export const servicesDataRed_EN = [
    {
        id: "testy",
        title: "Penetration Tests",
        title2: "",
        titleAboutService: "Why is it worth conducting penetration tests?",
        url: "/dashboard/red/services/testy",
        urlImage: "/assets/img/red/parciple/key.png",
        headerImg: "/assets/img/red/services/pene.png",
        position: "top",
        size: 0.40,
        description: "Penetration tests are an effective method of assessing IT infrastructure security by simulating real-world attacks.\n\nOur tests identify vulnerabilities in systems, applications, and networks, helping to minimize the risk of data breaches and cyberattacks.\n\nThanks to a professional approach, our experts deliver detailed reports with recommendations to support securing systems against potential threats.\n\nRegular penetration testing helps maintain a high level of security and ensures compliance with legal regulations and industry standards.",
        titleKrzysci: "Benefits of Penetration Tests:",
        titleZagrozenia: "Risks of Not Conducting Penetration Tests:",
        //icon BLUE
        iconsTop: [
            {
                id: 1,
                image: "/assets/img/icons/zabezpieczenie.svg",
                title: "Vulnerability Identification",
                desc: "Detecting potential gaps and weaknesses in IT systems.",
            },
            {
                id: 2,
                image: "/assets/img/icons/monitoring.png",
                title: "Compliance",
                desc: "Ensuring compliance with regulatory and security standards.",
            },
            {
                id: 3,
                image: "/assets/img/icons/ochrona.svg",
                title: "Data Protection",
                desc: "Protection against accidental data leaks.",
            },
            {
                id: 4,
                image: "/assets/img/icons/rodo.svg",
                title: "Proactiveness",
                desc: "A proactive approach to securing IT systems.",
            },
            {
                id: 5,
                image: "/assets/img/icons/zaufanie.svg",
                title: "Reliability",
                desc: "Building trust among clients and business partners.",
            },
            {
                id: 6,
                image: "/assets/img/icons/zapobieganie.svg",
                title: "Detailed Reports",
                desc: "Providing comprehensive analyses and recommendations to improve security.",
            },
        ],
        //red
        iconsRed: [
            {
                id: 1,
                image: "/assets/img/icons/utrata.svg",
                title: "Susceptibility to Attacks",
                desc: "Higher risk of security breaches by cybercriminals.",
            },
            {
                id: 2,
                image: "/assets/img/icons/kara.svg",
                title: "Data Loss",
                desc: "Loss of confidential information and damage to company reputation.",
            },
            {
                id: 3,
                image: "/assets/img/icons/ryzyko.svg",
                title: "Financial Penalties",
                desc: "Risk of high fines for non-compliance with regulations, e.g., GDPR.",
            },
            {
                id: 4,
                image: "/assets/img/icons/przestoje.png",
                title: "Lack of Awareness",
                desc: "Unawareness of existing security gaps.",
            },
            {
                id: 5,
                image: "/assets/img/icons/kradziez.svg",
                title: "Operational Downtime",
                desc: "Disruptions caused by attacks on infrastructure.",
            },
            {
                id: 6,
                image: "/assets/img/icons/kontrola.svg",
                title: "Data Theft",
                desc: "Risk of losing intellectual property and confidential information.",
            },
        ],
        doZapamietaniaTop: [
            {
                id: 1,
                image: "/assets/img/icons/red/zapobieganie1.svg",
                title: "Increases Security",
                desc: "Penetration tests are the foundation of preventing cyber threats.",
            },
            {
                id: 2,
                image: "/assets/img/icons/red/zabezpieczenie1.svg",
                title: "Ensures Compliance",
                desc: "Helps meet legal regulations and industry standards.",
            },
        ],
        doZapamietaniaBottom: [
            {
                id: 1,
                image: "/assets/img/icons/red/rodo1.svg",
                title: "Provides Reports",
                desc: "Detailed reports help implement corrective actions.",
            },
            {
                id: 2,
                image: "/assets/img/icons/red/ochrona1.svg",
                title: "Proactive Approach",
                desc: "Regular testing enables anticipating threats.",
            },
        ],
        FAQLeft: [
            {
                id: 1,
                title: "What are penetration tests?",
                content: "Penetration tests simulate attacks on IT systems to identify potential vulnerabilities and threats.",
            },
            {
                id: 2,
                title: "What systems can be tested?",
                content: "Tests can include web applications, network infrastructure, mobile systems, and cloud environments.",
            },
            {
                id: 3,
                title: "Do penetration tests disrupt system operations?",
                content: "Professional tests are conducted in a controlled manner to minimize the risk of disruptions.",
            },
            {
                id: 4,
                title: "How long does a penetration test take?",
                content: "The duration depends on the complexity of the infrastructure, typically taking a few days to several weeks.",
            },
            {
                id: 5,
                title: "Are test results confidential?",
                content: "Yes, all test results and details are strictly confidential and used solely to improve organizational security.",
            },
            {
                id: 6,
                title: "How often should tests be conducted?",
                content: "We recommend regular testing, especially after implementing new systems or infrastructure changes.",
            },
        ],
        FAQRight: [
            {
                id: 7,
                title: "Are penetration tests compliant with legal regulations?",
                content: "Yes, all our tests are conducted in accordance with applicable regulations and ethical standards.",
            },
            {
                id: 8,
                title: "What are the benefits of penetration tests?",
                content: "Tests help detect vulnerabilities, improve security, and increase awareness of threats within the organization.",
            },
            {
                id: 9,
                title: "Can tests include IoT devices?",
                content: "Yes, we offer security testing for IoT devices and related infrastructure.",
            },
            {
                id: 10,
                title: "Do penetration tests help meet regulatory requirements?",
                content: "Yes, our tests help organizations meet the requirements of regulations such as GDPR and PCI-DSS.",
            },
            {
                id: 11,
                title: "What are the main steps after the test?",
                content: "After completing the test, we provide a report with recommendations and an action plan.",
            },
            {
                id: 12,
                title: "Can I get the report in Polish?",
                content: "Yes, we offer reports in Polish or English, depending on the client's preference.",
            },
        ],
        filter: "testy",
        filter2: "one-time",
    },
    {
        id: "socjotechniczne",
        title: "Social Engineering Tests",
        title2: "",
        titleAboutService: "Why is it worth conducting social engineering tests?",
        url: "/dashboard/red/services/socjotechniczne",
        urlImage: "/assets/img/red/parciple/testy.svg",
        headerImg: "/assets/img/red/services/socjot.png",
        position: "center",
        size: 3.45,
        description: "Social engineering tests are a form of evaluation that simulates attacks targeting the human factor to identify gaps in employee security awareness.\n\nOur tests use manipulation and social engineering techniques, such as phishing, pretexting, or baiting, to assess staff reactions to potential threats.\n\nThanks to social engineering tests, an organization can effectively increase employee security awareness, implement appropriate training, and reduce risks associated with the weakest link – humans.\n\nThese tests not only detect problems but also help build a culture of security within the organization.",
        titleKrzysci: "Benefits of Social Engineering Tests:",
        titleZagrozenia: "Risks of Not Conducting Social Engineering Tests:",
        iconsTop: [
            {
                id: 1,
                image: "/assets/img/icons/zabezpieczenie.svg",
                title: "Increased Awareness",
                desc: "Raising employee knowledge about social engineering threats.",
            },
            {
                id: 2,
                image: "/assets/img/icons/monitoring.png",
                title: "Improved Response",
                desc: "Enhancing procedures for responding to attack attempts.",
            },
            {
                id: 3,
                image: "/assets/img/icons/ochrona.svg",
                title: "Education",
                desc: "Implementing training tailored to identified gaps.",
            },
            {
                id: 4,
                image: "/assets/img/icons/rodo.svg",
                title: "Building Trust",
                desc: "Strengthening trust among clients and business partners.",
            },
            {
                id: 5,
                image: "/assets/img/icons/zaufanie.svg",
                title: "Proactive Prevention",
                desc: "Reducing the risk of data leaks through social engineering manipulations.",
            },
            {
                id: 6,
                image: "/assets/img/icons/zapobieganie.svg",
                title: "Increased Security",
                desc: "Improving organizational resilience to internal and external threats.",
            },
        ],
        iconsRed: [
            {
                id: 1,
                image: "/assets/img/icons/utrata.svg",
                title: "Phishing Vulnerability",
                desc: "Increased risk of successful phishing attacks.",
            },
            {
                id: 2,
                image: "/assets/img/icons/kara.svg",
                title: "Data Leakage",
                desc: "Unintentional sharing of confidential information.",
            },
            {
                id: 3,
                image: "/assets/img/icons/ryzyko.svg",
                title: "Loss of Control",
                desc: "High risk of successful social engineering attacks.",
            },
            {
                id: 4,
                image: "/assets/img/icons/przestoje.png",
                title: "Reputation Damage",
                desc: "Serious image-related consequences for the organization.",
            },
            {
                id: 5,
                image: "/assets/img/icons/kradziez.svg",
                title: "Risk of Penalties",
                desc: "Penalties for security breaches, e.g., related to GDPR.",
            },
            {
                id: 6,
                image: "/assets/img/icons/kontrola.svg",
                title: "Lack of Awareness",
                desc: "Employee unawareness of social engineering threats.",
            },
        ],
        doZapamietaniaTop: [
            {
                id: 1,
                image: "/assets/img/icons/red/zapobieganie1.svg",
                title: "Education",
                desc: "Tests teach employees to recognize and avoid threats.",
            },
            {
                id: 2,
                image: "/assets/img/icons/red/zabezpieczenie1.svg",
                title: "Proactiveness",
                desc: "Helps build a security culture within the organization.",
            },
        ],
        doZapamietaniaBottom: [
            {
                id: 1,
                image: "/assets/img/icons/red/rodo1.svg",
                title: "Safe Environment",
                desc: "Increases resistance to social engineering attempts.",
            },
            {
                id: 2,
                image: "/assets/img/icons/red/ochrona1.svg",
                title: "Building Trust",
                desc: "Creates trust in the company among clients and partners.",
            },
        ],
        FAQLeft: [
            {
                id: 1,
                title: "What are social engineering tests?",
                content: "These are simulations of attacks targeting the human factor to identify employee vulnerabilities to manipulations.",
            },
            {
                id: 2,
                title: "What techniques are used in the tests?",
                content: "Tests include phishing, pretexting, baiting, tailgating, and other manipulation methods.",
            },
            {
                id: 3,
                title: "Are the tests confidential?",
                content: "Yes, all results and details of the tests remain confidential and serve only to improve organizational security.",
            },
            {
                id: 4,
                title: "What is the process for the tests?",
                content: "We start with an organization analysis, conduct simulations, and then deliver a report with recommendations.",
            },
            {
                id: 5,
                title: "Are employees informed about the tests?",
                content: "In most cases, tests are conducted without prior knowledge of employees to obtain realistic results.",
            },
            {
                id: 6,
                title: "Can the tests be tailored to the company’s specifics?",
                content: "Yes, our tests are tailored to the needs and specifics of the client's operations.",
            },
        ],
        FAQRight: [
            {
                id: 7,
                title: "What are the benefits of social engineering tests?",
                content: "Tests increase awareness, improve security procedures, and minimize the risk of breaches.",
            },
            {
                id: 8,
                title: "Are social engineering tests legal?",
                content: "Yes, they are conducted in compliance with the law and with the consent of the company’s management.",
            },
            {
                id: 9,
                title: "How often should tests be conducted?",
                content: "We recommend conducting tests at least once a year or after structural changes in the company.",
            },
            {
                id: 10,
                title: "Do the tests include remote employees?",
                content: "Yes, our tests can also cover remote employees.",
            },
            {
                id: 11,
                title: "Can the tests indicate the need for additional training?",
                content: "Yes, the test results help identify areas for improvement and the need for training implementation.",
            },
            {
                id: 12,
                title: "Can reports be provided in Polish?",
                content: "Yes, reports can be prepared in Polish or English, depending on client preferences.",
            },
        ],
        filter: "testy",
        filter2: "one-time",
    },
    {
        id: "testybezpieczenstwafizycznego",
        title: "Physical Security Tests",
        title2: "",
        url: "/dashboard/red/services/testybezpieczenstwafizycznego",
        urlImage: "/assets/img/red/parciple/safe.png",
        headerImg: "/assets/img/red/services/bez.png",
        position: "center",
        size: 1.1,
        titleAboutService: "Why is it worth conducting physical security tests?",
        description: "Physical security tests evaluate the effectiveness of safeguards against unauthorized access to an organization's infrastructure.\n\nOur tests include break-in simulations, access procedure evaluations, monitoring system reviews, and analysis of gaps in physical security.\n\nThanks to physical security tests, an organization can identify weaknesses in protection systems, improve procedures, and ensure the safety of its resources.\n\nRegular tests help minimize risks associated with physical threats such as break-ins, sabotage, or data theft.",
        titleKrzysci: "Benefits of Physical Security Tests:",
        titleZagrozenia: "Risks of Not Conducting Physical Security Tests:",
        iconsTop: [
            {
                id: 1,
                image: "/assets/img/icons/zabezpieczenie.svg",
                title: "Increased Protection",
                desc: "More effective safeguarding against unauthorized access.",
            },
            {
                id: 2,
                image: "/assets/img/icons/monitoring.png",
                title: "Vulnerability Identification",
                desc: "Detection of weaknesses in physical security systems.",
            },
            {
                id: 3,
                image: "/assets/img/icons/ochrona.svg",
                title: "Improved Procedures",
                desc: "Enhancing access rules and incident response procedures.",
            },
            {
                id: 4,
                image: "/assets/img/icons/rodo.svg",
                title: "Reliability",
                desc: "Building trust among clients and business partners.",
            },
            {
                id: 5,
                image: "/assets/img/icons/zaufanie.svg",
                title: "Better Safeguards",
                desc: "Increasing the effectiveness of monitoring and access control systems.",
            },
            {
                id: 6,
                image: "/assets/img/icons/zapobieganie.svg",
                title: "Meeting Requirements",
                desc: "Providing detailed reports with recommendations to improve security.",
            },
        ],
        iconsRedTop: [
            {
                id: 1,
                image: "/assets/img/icons/utrata.svg",
                title: "Theft",
                desc: "Risk of theft of equipment, data, or intellectual property.",
            },
            {
                id: 2,
                image: "/assets/img/icons/kara.svg",
                title: "Break-ins",
                desc: "Increased susceptibility to physical break-ins.",
            },
            {
                id: 3,
                image: "/assets/img/icons/ryzyko.svg",
                title: "Sabotage",
                desc: "Risk of intentional damage to organizational infrastructure.",
            },
            {
                id: 4,
                image: "/assets/img/icons/przestoje.png",
                title: "Reputation Damage",
                desc: "Image-related consequences due to insufficient protection.",
            },
            {
                id: 5,
                image: "/assets/img/icons/kradziez.svg",
                title: "Financial Penalties",
                desc: "Penalties resulting from not meeting physical security requirements.",
            },
            {
                id: 6,
                image: "/assets/img/icons/kontrola.svg",
                title: "Lack of Awareness",
                desc: "Unawareness of existing security gaps.",
            },
        ],
        doZapamietaniaTop: [
            {
                id: 1,
                image: "/assets/img/icons/red/zapobieganie1.svg",
                title: "Infrastructure Protection",
                desc: "Tests allow better protection of physical and organizational data assets.",
            },
            {
                id: 2,
                image: "/assets/img/icons/red/zabezpieczenie1.svg",
                title: "Procedure Optimization",
                desc: "Helps refine protection and access rules.",
            },
        ],
        doZapamietaniaBottom: [
            {
                id: 1,
                image: "/assets/img/icons/red/rodo1.svg",
                title: "Safe Environment",
                desc: "Increases the safety of facilities and employees.",
            },
            {
                id: 2,
                image: "/assets/img/icons/red/ochrona1.svg",
                title: "Meeting Standards",
                desc: "Ensures compliance with legal and industry requirements.",
            },
        ],
        FAQLeft: [
            {
                id: 1,
                title: "What are physical security tests?",
                content: "These are tests evaluating the effectiveness of physical safeguards for infrastructure, such as locks, monitoring, or access control.",
            },
            {
                id: 2,
                title: "What techniques are used in the tests?",
                content: "Break-in simulations, monitoring evaluations, security procedure analysis, and access control system tests.",
            },
            {
                id: 3,
                title: "Are the tests legal?",
                content: "Yes, tests are conducted with the consent of the company management and in accordance with applicable laws.",
            },
            {
                id: 4,
                title: "Do the tests impact daily business operations?",
                content: "Tests are conducted in a way that minimizes disruptions to organizational activities.",
            },
            {
                id: 5,
                title: "What does the test report include?",
                content: "The report contains detailed test results, identified gaps, and recommendations for improving security.",
            },
            {
                id: 6,
                title: "How often should tests be conducted?",
                content: "We recommend conducting tests at least once a year or after implementing new security systems.",
            },
        ],
        FAQRight: [
            {
                id: 7,
                title: "What systems can be tested?",
                content: "Tests can cover monitoring, access control, mechanical safeguards, and protection procedures.",
            },
            {
                id: 8,
                title: "Can the tests include server room protection?",
                content: "Yes, tests can include physical security of server rooms and other key locations.",
            },
            {
                id: 9,
                title: "Do the tests identify procedural errors?",
                content: "Yes, tests help identify and improve inefficient security procedures.",
            },
            {
                id: 10,
                title: "Can the tests consider sabotage prevention?",
                content: "Yes, we also evaluate potential sabotage risks and ways to mitigate them.",
            },
            {
                id: 11,
                title: "Do you offer help in improving detected gaps?",
                content: "Yes, we provide support in developing and implementing effective solutions.",
            },
            {
                id: 12,
                title: "Do the tests consider both external and internal threats?",
                content: "Yes, our tests cover both external and internal threats, such as unauthorized employee access.",
            },
        ],
        filter: "testy",
        filter2: "one-time",
    },
    {
        id: "testyodpornoscinaatakiDDoS",
        title: "DDoS Attack Resilience Tests",
        title2: "",
        titleAboutService: "Why is it worth conducting DDoS attack resilience tests?",
        url: "/dashboard/red/services/testyodpornoscinaatakiDDoS",
        urlImage: "/assets/img/red/parciple/dds.svg",
        headerImg: "/assets/img/red/services/ddos.png",
        position: "bottom",
        size: 1,
        description: "DDoS resilience tests assess the ability of IT infrastructure to handle intense, targeted network traffic aimed at disrupting services.\n\nOur tests simulate various types of DDoS attacks to identify system weaknesses, improve performance, and enhance network security.\n\nWith these tests, organizations can prepare effective defense strategies, minimize downtime risks, and protect their reputation.\n\nRegular DDoS resilience testing is crucial to address the growing threats in the digital world.",
        titleKrzysci: "Benefits of DDoS Attack Resilience Tests:",
        titleZagrozenia: "Risks of Not Conducting DDoS Resilience Tests:",
        iconsTop: [
            {
                id: 1,
                image: "/assets/img/icons/zabezpieczenie.svg",
                title: "Improved Protection",
                desc: "Enhanced ability to defend against real DDoS attacks.",
            },
            {
                id: 2,
                image: "/assets/img/icons/monitoring.png",
                title: "Performance Optimization",
                desc: "Improved network and server infrastructure.",
            },
            {
                id: 3,
                image: "/assets/img/icons/ochrona.svg",
                title: "Faster Response",
                desc: "Better preparedness for sudden traffic surges.",
            },
            {
                id: 4,
                image: "/assets/img/icons/rodo.svg",
                title: "Effective Strategy",
                desc: "Development of a DDoS defense plan.",
            },
            {
                id: 5,
                image: "/assets/img/icons/zaufanie.svg",
                title: "Increased Security",
                desc: "Minimization of downtime risks and financial losses.",
            },
            {
                id: 6,
                image: "/assets/img/icons/zapobieganie.svg",
                title: "Standards Compliance",
                desc: "Ensuring compliance with regulatory and security standards.",
            },
        ],
        iconsRed: [
            {
                id: 1,
                image: "/assets/img/icons/utrata.svg",
                title: "Downtime",
                desc: "Risk of service disruptions in critical operations.",
            },
            {
                id: 2,
                image: "/assets/img/icons/kara.svg",
                title: "Financial Losses",
                desc: "Costs resulting from service unavailability.",
            },
            {
                id: 3,
                image: "/assets/img/icons/ryzyko.svg",
                title: "Reputation Damage",
                desc: "Negative impact on the company's image in the eyes of clients.",
            },
            {
                id: 4,
                image: "/assets/img/icons/przestoje.png",
                title: "Lack of Awareness",
                desc: "Unawareness of system weaknesses.",
            },
            {
                id: 5,
                image: "/assets/img/icons/kradziez.svg",
                title: "Vulnerability to Attacks",
                desc: "Increased effectiveness of DDoS attacks.",
            },
            {
                id: 6,
                image: "/assets/img/icons/kontrola.svg",
                title: "Penalties and Regulations",
                desc: "Potential consequences for failing to meet security requirements.",
            },
        ],
        doZapamietaniaTop: [
            {
                id: 1,
                image: "/assets/img/icons/red/zapobieganie1.svg",
                title: "Readiness",
                desc: "Tests prepare organizations for real DDoS attacks.",
            },
            {
                id: 2,
                image: "/assets/img/icons/red/zabezpieczenie1.svg",
                title: "Defense Plan",
                desc: "Helps develop an effective protection strategy.",
            },
        ],
        doZapamietaniaBottom: [
            {
                id: 1,
                image: "/assets/img/icons/red/rodo1.svg",
                title: "Enhanced Protection",
                desc: "Ensures service availability during critical moments.",
            },
            {
                id: 2,
                image: "/assets/img/icons/red/ochrona1.svg",
                title: "Increased Security",
                desc: "Minimizes financial and reputational risks.",
            },
        ],
        FAQLeft: [
            {
                id: 1,
                title: "What are DDoS attacks?",
                content: "DDoS (Distributed Denial of Service) attacks overload servers by sending massive requests from multiple sources.",
            },
            {
                id: 2,
                title: "What are the goals of DDoS tests?",
                content: "Tests assess system resilience and help organizations prepare for real threats.",
            },
            {
                id: 3,
                title: "Do tests affect system performance?",
                content: "Tests are conducted in a controlled manner to avoid infrastructure disruptions.",
            },
            {
                id: 4,
                title: "What does the test report include?",
                content: "The report includes resilience analysis, identified weaknesses, and recommendations for improving security.",
            },
            {
                id: 5,
                title: "Are tests legal?",
                content: "Yes, they are conducted with client consent and in compliance with applicable laws.",
            },
            {
                id: 6,
                title: "How often should DDoS tests be conducted?",
                content: "We recommend tests at least once a year or after changes in IT infrastructure.",
            },
        ],
        FAQRight: [
            {
                id: 7,
                title: "What systems can be tested?",
                content: "Tests can include servers, networks, web applications, and cloud services.",
            },
            {
                id: 8,
                title: "Do tests simulate different types of DDoS attacks?",
                content: "Yes, our tests simulate techniques such as volumetric, protocol-based, and application-layer attacks.",
            },
            {
                id: 9,
                title: "Do tests help identify the best solutions against DDoS?",
                content: "Yes, results highlight system vulnerabilities and effective protection strategies.",
            },
            {
                id: 10,
                title: "Do DDoS tests include real-time monitoring?",
                content: "Yes, we offer system behavior monitoring during attack simulations.",
            },
            {
                id: 11,
                title: "Do you provide post-test support?",
                content: "Yes, we offer assistance in implementing recommendations and defense strategies.",
            },
            {
                id: 12,
                title: "Do tests include protection against botnet attacks?",
                content: "Yes, we also analyze vulnerabilities to botnet attacks.",
            },
        ],
        filter: "testy",
        filter2: "one-time",
    },
    {
        id: "skanypodatnosci",
        title: "Vulnerability Scans",
        title2: "",
        titleAboutService: "Why is it worth performing regular vulnerability scans?",
        url: "/dashboard/red/services/skanypodatnosci",
        urlImage: "/assets/img/red/parciple/test.svg",
        headerImg: "/assets/img/red/services/podatnosc.png",
        position: "center",
        size: 1,
        description: "Vulnerability scans are automated tests that identify weaknesses in IT systems, applications, and networks.\n\nOur services include regular infrastructure scanning to detect potential security threats, such as outdated software, configuration errors, or zero-day vulnerabilities.\n\nWith vulnerability scans, organizations can quickly respond to threats, apply patches, and minimize attack risks.\n\nRegular scanning is a key element of IT security management that helps maintain high system resilience against cyber threats.",
        titleKrzysci: "Benefits of Regular Vulnerability Scans:",
        titleZagrozenia: "Risks of Not Conducting Vulnerability Scans:",
        iconsTop: [
            {
                id: 1,
                image: "/assets/img/icons/zabezpieczenie.svg",
                title: "Early Detection",
                desc: "Quick identification of weaknesses in IT systems.",
            },
            {
                id: 2,
                image: "/assets/img/icons/monitoring.png",
                title: "Regulatory Compliance",
                desc: "Ensuring compliance with security standards and legal regulations.",
            },
            {
                id: 3,
                image: "/assets/img/icons/ochrona.svg",
                title: "Data Protection",
                desc: "Minimizing the risk of data leaks by eliminating vulnerabilities.",
            },
            {
                id: 4,
                image: "/assets/img/icons/rodo.svg",
                title: "Efficiency",
                desc: "Automated scanning improves security management.",
            },
            {
                id: 5,
                image: "/assets/img/icons/zaufanie.svg",
                title: "Detailed Reports",
                desc: "Providing reports with prioritized fixes for identified vulnerabilities.",
            },
            {
                id: 6,
                image: "/assets/img/icons/zapobieganie.svg",
                title: "Proactiveness",
                desc: "Preventing incidents by early threat mitigation.",
            },
        ],
        iconsRed: [
            {
                id: 1,
                image: "/assets/img/icons/utrata.svg",
                title: "Undiscovered Vulnerabilities",
                desc: "Lack of awareness of existing threats in systems.",
            },
            {
                id: 2,
                image: "/assets/img/icons/kara.svg",
                title: "Data Leakage",
                desc: "Increased risk of unauthorized access and data leaks.",
            },
            {
                id: 3,
                image: "/assets/img/icons/ryzyko.svg",
                title: "Susceptibility to Attacks",
                desc: "Greater effectiveness of cyberattacks on unpatched systems.",
            },
            {
                id: 4,
                image: "/assets/img/icons/przestoje.png",
                title: "Reputation Damage",
                desc: "Image-related consequences due to security breaches.",
            },
            {
                id: 5,
                image: "/assets/img/icons/kradziez.svg",
                title: "Lack of Awareness",
                desc: "Unawareness of configuration errors and system gaps.",
            },
            {
                id: 6,
                image: "/assets/img/icons/kontrola.svg",
                title: "Penalties and Regulations",
                desc: "Potential legal consequences of security violations.",
            },
        ],
        doZapamietaniaTop: [
            {
                id: 1,
                image: "/assets/img/icons/red/zapobieganie1.svg",
                title: "Early Detection",
                desc: "Vulnerability scans help identify threats before they are exploited.",
            },
            {
                id: 2,
                image: "/assets/img/icons/red/zabezpieczenie1.svg",
                title: "Proactive Approach",
                desc: "Ensures better preparation for potential attacks.",
            },
        ],
        doZapamietaniaBottom: [
            {
                id: 1,
                image: "/assets/img/icons/red/rodo1.svg",
                title: "Ensuring Compliance",
                desc: "Helps meet regulatory requirements and security standards.",
            },
            {
                id: 2,
                image: "/assets/img/icons/red/ochrona1.svg",
                title: "Resource Protection",
                desc: "Minimizes financial and reputational risks.",
            },
        ],
        FAQLeft: [
            {
                id: 1,
                title: "What are vulnerability scans?",
                content: "Automated tests identifying weaknesses in IT systems, applications, and networks.",
            },
            {
                id: 2,
                title: "What systems can be scanned?",
                content: "Scans can include servers, web applications, network devices, and cloud systems.",
            },
            {
                id: 3,
                title: "Do vulnerability scans disrupt system performance?",
                content: "Scans are conducted in a controlled manner to avoid disruptions.",
            },
            {
                id: 4,
                title: "What does a vulnerability scan report include?",
                content: "The report contains detailed information about identified vulnerabilities and remedial recommendations.",
            },
            {
                id: 5,
                title: "How often should vulnerability scans be conducted?",
                content: "We recommend regular scanning, at least monthly or after major system changes.",
            },
            {
                id: 6,
                title: "Are vulnerability scans compliant with legal regulations?",
                content: "Yes, scans help meet requirements like GDPR, PCI-DSS, or ISO 27001.",
            },
        ],
        FAQRight: [
            {
                id: 7,
                title: "Do scans include IoT devices?",
                content: "Yes, we offer scanning for IoT devices and other infrastructure components.",
            },
            {
                id: 8,
                title: "Do vulnerability scans detect configuration errors?",
                content: "Yes, our tools identify both configuration errors and outdated software.",
            },
            {
                id: 9,
                title: "What tools are used for scans?",
                content: "We use advanced enterprise-grade tools that provide detailed analyses.",
            },
            {
                id: 10,
                title: "Do vulnerability scans help with patch management?",
                content: "Yes, reports indicate which systems require software updates.",
            },
            {
                id: 11,
                title: "Do you provide support for fixing identified vulnerabilities?",
                content: "Yes, we assist in implementing appropriate patches and fixes.",
            },
            {
                id: 12,
                title: "Do vulnerability scans include zero-day threat analysis?",
                content: "Our tools also identify zero-day threats known at the time of scanning.",
            },
        ],
        filter: "monitoringinfrastruktury",
        filter2: "one-time",
    },
    {
        id: "szkoleniezcyberbezpieczenstwa",
        title: "Cybersecurity Training",
        title2: "",
        titleAboutService: "Why invest in cybersecurity training?",
        url: "/dashboard/red/services/szkolenie",
        urlImage: "/assets/img/red/parciple/technical.svg",
        headerImg: "/assets/img/red/services/podatnosc.png",
        position: "top",
        size: 0.60,
        description: "Cybersecurity training is a key element in building organizational awareness and protection against cyber threats.\n\nOur training includes practical exercises, real-world threat scenarios, and an overview of the latest attack techniques and defense methods.\n\nThrough our training, employees learn to identify threats such as phishing, social engineering attacks, and malware, and respond to them appropriately.\n\nInvesting in cybersecurity training minimizes the risk of incidents, enhances the company's resilience to attacks, and fosters a culture of security within the organization.",
        titleKrzysci: "Benefits of participating in cybersecurity training:",
        titleZagrozenia: "Risks of not conducting training:",
        iconsTop: [
            {
                id: 1,
                image: "/assets/img/icons/zabezpieczenie.svg",
                title: "Identifying Gaps",
                desc: "Detection of potential vulnerabilities and weaknesses in IT systems.",
            },
            {
                id: 2,
                image: "/assets/img/icons/monitoring.png",
                title: "Compliance",
                desc: "Ensuring compliance with regulatory requirements and security standards.",
            },
            {
                id: 3,
                image: "/assets/img/icons/ochrona.svg",
                title: "Data Protection",
                desc: "Preventing accidental data breaches.",
            },
            {
                id: 4,
                image: "/assets/img/icons/rodo.svg",
                title: "Proactiveness",
                desc: "Proactive approach to securing IT systems.",
            },
            {
                id: 5,
                image: "/assets/img/icons/zaufanie.svg",
                title: "Credibility",
                desc: "Building trust among clients and business partners.",
            },
            {
                id: 6,
                image: "/assets/img/icons/zapobieganie.svg",
                title: "Detailed Reports",
                desc: "Providing comprehensive analyses and recommendations for improving security.",
            },
        ],
        iconsRed: [
            {
                id: 1,
                image: "/assets/img/icons/utrata.svg",
                title: "Vulnerability to Attacks",
                desc: "Higher risk of security breaches by cybercriminals.",
            },
            {
                id: 2,
                image: "/assets/img/icons/kara.svg",
                title: "Data Loss",
                desc: "Loss of confidential information and damage to company reputation.",
            },
            {
                id: 3,
                image: "/assets/img/icons/ryzyko.svg",
                title: "Financial Penalties",
                desc: "Risk of high fines for non-compliance with regulations, e.g., GDPR.",
            },
            {
                id: 4,
                image: "/assets/img/icons/przestoje.png",
                title: "Lack of Awareness",
                desc: "Unawareness of existing security gaps.",
            },
            {
                id: 5,
                image: "/assets/img/icons/kradziez.svg",
                title: "Operational Downtime",
                desc: "Interruptions in operations caused by attacks on infrastructure.",
            },
            {
                id: 6,
                image: "/assets/img/icons/kontrola.svg",
                title: "Data Theft",
                desc: "Risk of losing intellectual property and confidential information.",
            },
        ],
        doZapamietaniaTop: [
            {
                id: 1,
                image: "/assets/img/icons/red/zapobieganie1.svg",
                title: "Enhances Security",
                desc: "Penetration testing is the cornerstone of preventing cyber threats.",
            },
            {
                id: 2,
                image: "/assets/img/icons/red/zabezpieczenie1.svg",
                title: "Ensures Compliance",
                desc: "Helps meet legal and industry standards.",
            },
        ],
        doZapamietaniaBottom: [
            {
                id: 1,
                image: "/assets/img/icons/red/rodo1.svg",
                title: "Delivers Reports",
                desc: "Detailed reports help implement corrective actions.",
            },
            {
                id: 2,
                image: "/assets/img/icons/red/ochrona1.svg",
                title: "Proactive Approach",
                desc: "Regular tests enable anticipating and addressing threats.",
            },
        ],
        FAQLeft: [
            {
                id: 1,
                title: "What is cybersecurity training?",
                content: "These are workshops and educational sessions teaching employees to identify and respond to threats.",
            },
            {
                id: 2,
                title: "Who is the training for?",
                content: "The training is designed for employees at all levels of the organization.",
            },
            {
                id: 3,
                title: "Is the training practical?",
                content: "Yes, our training includes exercises in realistic threat scenarios.",
            },
            {
                id: 4,
                title: "Can the training be customized for the company?",
                content: "Yes, we offer training tailored to the organization's specifics and needs.",
            },
            {
                id: 5,
                title: "How often should training be organized?",
                content: "We recommend conducting training at least once a year.",
            },
            {
                id: 6,
                title: "Does the training help meet regulatory requirements?",
                content: "Yes, it helps fulfill regulations such as GDPR or NIS2.",
            },
        ],
        FAQRight: [
            {
                id: 7,
                title: "What topics does the training cover?",
                content: "Phishing, social engineering, malware, password management, and other key aspects.",
            },
            {
                id: 8,
                title: "Is the training available online?",
                content: "Yes, we offer both on-site and online training.",
            },
            {
                id: 9,
                title: "Do you provide certificates of completion?",
                content: "Yes, participants receive certificates confirming their participation in the training.",
            },
            {
                id: 10,
                title: "Does the training include the latest threats?",
                content: "Yes, our training is regularly updated with the latest trends and attack techniques.",
            },
            {
                id: 11,
                title: "What are the benefits for the company after the training?",
                content: "Increased resilience to attacks and fostering a culture of security within the organization.",
            },
            {
                id: 12,
                title: "Can training be combined with other services?",
                content: "Yes, training can be part of a comprehensive security strategy.",
            },
        ],
        filter: "szkolenia",
        filter2: "one-time",
    },
    {
        id: "dlakadryinformatycznej",
        title: "Training for IT Staff",
        title2: "",
        titleAboutService: "Why train your IT staff?",
        url: "/dashboard/red/services/dlakadryinformatycznej",
        urlImage: "/assets/img/red/parciple/SZBI.svg",
        headerImg: "/assets/img/red/services/podatnosc.png",
        position: "center",
        size: 3.4,
        description: "Training for IT staff focuses on advanced topics related to cybersecurity, IT infrastructure management, and the latest technologies.\n\nOur training programs include practical workshops that enable IT teams to enhance their skills in threat detection, incident response, and security system management.\n\nThrough this training, organizations can improve the effectiveness of their IT teams, reduce the risk of cyberattacks, and implement best practices in IT management.\n\nTraining for IT staff is an investment that brings tangible benefits in the form of better protection, efficiency, and regulatory compliance.",
        titleKrzysci: "Benefits of training for IT staff:",
        titleZagrozenia: "Risks of not conducting training:",
        iconsTop: [
            {
                id: 1,
                image: "/assets/img/icons/zabezpieczenie.svg",
                title: "Advanced Knowledge",
                desc: "Expanding the IT team's competencies in critical areas of security.",
            },
            {
                id: 2,
                image: "/assets/img/icons/monitoring.png",
                title: "Increased Efficiency",
                desc: "Better management of systems and responses to threats.",
            },
            {
                id: 3,
                image: "/assets/img/icons/ochrona.svg",
                title: "New Technologies",
                desc: "Gaining knowledge about the latest tools and defensive techniques.",
            },
            {
                id: 4,
                image: "/assets/img/icons/rodo.svg",
                title: "Better Planning",
                desc: "Developing and implementing effective security strategies.",
            },
            {
                id: 5,
                image: "/assets/img/icons/zaufanie.svg",
                title: "Compliance",
                desc: "Ensuring compliance with regulations such as GDPR or NIS2.",
            },
            {
                id: 6,
                image: "/assets/img/icons/zapobieganie.svg",
                title: "Building Trust",
                desc: "Enhancing the credibility of the IT team within the organization.",
            },
        ],
        iconsRed: [
            {
                id: 1,
                image: "/assets/img/icons/utrata.svg",
                title: "Lack of Advanced Knowledge",
                desc: "Increased risk of errors and inefficient system management.",
            },
            {
                id: 2,
                image: "/assets/img/icons/kara.svg",
                title: "Vulnerability to Attacks",
                desc: "Higher risk of successful cyberattacks.",
            },
            {
                id: 3,
                image: "/assets/img/icons/ryzyko.svg",
                title: "Financial Penalties",
                desc: "Non-compliance with regulations can lead to significant fines.",
            },
            {
                id: 4,
                image: "/assets/img/icons/przestoje.png",
                title: "Operational Downtime",
                desc: "Risk of prolonged downtime in case of incidents.",
            },
            {
                id: 5,
                image: "/assets/img/icons/kradziez.svg",
                title: "Data Breach",
                desc: "Inadequate response to threats increases the risk of data loss.",
            },
            {
                id: 6,
                image: "/assets/img/icons/kontrola.svg",
                title: "Risk",
                desc: "Security breaches due to lack of IT resource monitoring.",
            },
        ],
        doZapamietaniaTop: [
            {
                id: 1,
                image: "/assets/img/icons/red/zapobieganie1.svg",
                title: "Advanced Knowledge",
                desc: "Training enhances IT team skills in critical areas.",
            },
            {
                id: 2,
                image: "/assets/img/icons/red/zabezpieczenie1.svg",
                title: "Proactive Approach",
                desc: "Enables predicting and preventing threats.",
            },
        ],
        doZapamietaniaBottom: [
            {
                id: 1,
                image: "/assets/img/icons/red/rodo1.svg",
                title: "Regulatory Compliance",
                desc: "Training helps meet legal and industry requirements.",
            },
            {
                id: 2,
                image: "/assets/img/icons/red/ochrona1.svg",
                title: "Increased Efficiency",
                desc: "Enables efficient system management and incident response.",
            },
        ],
        FAQLeft: [
            {
                id: 1,
                title: "What is training for IT staff?",
                content: "Advanced courses and workshops that enhance the IT team's skills in security and system management.",
            },
            {
                id: 2,
                title: "Who is the training for?",
                content: "For system administrators, security specialists, and other IT team members.",
            },
            {
                id: 3,
                title: "What topics does the training cover?",
                content: "Infrastructure management, incident response, threat detection, new technologies, and regulations.",
            },
            {
                id: 4,
                title: "Is the training practical?",
                content: "Yes, our training includes practical exercises and simulations of real incidents.",
            },
            {
                id: 5,
                title: "How often should training be conducted?",
                content: "We recommend regular training, at least once a year or after implementing new technologies.",
            },
            {
                id: 6,
                title: "Does the training help with regulatory compliance?",
                content: "Yes, our courses comply with current legal requirements and security standards.",
            },
        ],
        FAQRight: [
            {
                id: 7,
                title: "Does the training include the latest technologies?",
                content: "Yes, our courses are updated with the latest trends and technological solutions.",
            },
            {
                id: 8,
                title: "Can the training be customized for the company?",
                content: "Yes, we offer training tailored to the client's specificity and requirements.",
            },
            {
                id: 9,
                title: "Do you offer online training?",
                content: "Yes, we offer both on-site and remote training.",
            },
            {
                id: 10,
                title: "Do participants receive certificates?",
                content: "Yes, after completing the training, each participant receives a certificate.",
            },
            {
                id: 11,
                title: "Does the training include case study analysis?",
                content: "Yes, we analyze real incidents to better prepare participants.",
            },
            {
                id: 12,
                title: "What are the benefits for the organization?",
                content: "Increased IT team competencies, better protection against threats, and efficient system management.",
            },
        ],
        filter: "szkolenia",
        filter2: "one-time",
    },
    {
        id: "wsparcie_w_obsludze_incydentu",
        title: "Incident Response Support",
        title2: "",
        titleAboutService: "Why use incident response support?",
        url: "/dashboard/red/services/wsparcie_w_obsludze_incydentu",
        urlImage: "/assets/img/red/parciple/technical.svg",
        headerImg: "/assets/img/red/services/podatnosc.png",
        position: "center",
        size: 0.65,
        description: "Our incident response support service provides immediate assistance in crisis situations related to cybersecurity.\n\nOur experts help quickly detect and neutralize threats, minimize their impact, and restore normal functioning of IT systems.\n\nThe support includes incident analysis, implementation of corrective actions, and advice on preventing similar situations in the future.\n\nWith our help, organizations can effectively manage incidents, minimizing financial, operational, and reputational losses.",
        titleKrzysci: "Benefits of incident response support:",
        titleZagrozenia: "Risks of lacking professional support:",
        iconsTop: [
            {
                id: 1,
                image: "/assets/img/icons/zabezpieczenie.svg",
                title: "Identifying Gaps",
                desc: "Detection of potential vulnerabilities and weaknesses in IT systems.",
            },
            {
                id: 2,
                image: "/assets/img/icons/monitoring.png",
                title: "Compliance",
                desc: "Ensuring compliance with regulatory requirements and security standards.",
            },
            {
                id: 3,
                image: "/assets/img/icons/ochrona.svg",
                title: "Data Protection",
                desc: "Protection against accidental data leaks.",
            },
            {
                id: 4,
                image: "/assets/img/icons/rodo.svg",
                title: "Proactiveness",
                desc: "Proactive approach to securing IT systems.",
            },
            {
                id: 5,
                image: "/assets/img/icons/zaufanie.svg",
                title: "Credibility",
                desc: "Building trust among clients and business partners.",
            },
            {
                id: 6,
                image: "/assets/img/icons/zapobieganie.svg",
                title: "Detailed Reports",
                desc: "Providing comprehensive analyses and recommendations for improving security.",
            },
        ],
        iconsRed: [
            {
                id: 1,
                image: "/assets/img/icons/utrata.svg",
                title: "Vulnerability to Attacks",
                desc: "Higher risk of security breaches by cybercriminals.",
            },
            {
                id: 2,
                image: "/assets/img/icons/kara.svg",
                title: "Data Loss",
                desc: "Loss of confidential information and damage to company reputation.",
            },
            {
                id: 3,
                image: "/assets/img/icons/ryzyko.svg",
                title: "Financial Penalties",
                desc: "Risk of high fines for non-compliance with regulations, e.g., GDPR.",
            },
            {
                id: 4,
                image: "/assets/img/icons/przestoje.png",
                title: "Lack of Awareness",
                desc: "Unawareness of existing vulnerabilities in security.",
            },
            {
                id: 5,
                image: "/assets/img/icons/kradziez.svg",
                title: "Operational Downtime",
                desc: "Interruptions in operations caused by infrastructure attacks.",
            },
            {
                id: 6,
                image: "/assets/img/icons/kontrola.svg",
                title: "Data Theft",
                desc: "Risk of losing intellectual property and confidential information.",
            },
        ],
        doZapamietaniaTop: [
            {
                id: 1,
                image: "/assets/img/icons/red/zapobieganie1.svg",
                title: "Enhances Security",
                desc: "Incident response support strengthens organizational resilience to threats.",
            },
            {
                id: 2,
                image: "/assets/img/icons/red/zabezpieczenie1.svg",
                title: "Ensures Compliance",
                desc: "Helps meet legal and industry standards.",
            },
        ],
        doZapamietaniaBottom: [
            {
                id: 1,
                image: "/assets/img/icons/red/rodo1.svg",
                title: "Delivers Reports",
                desc: "Detailed reports help implement corrective actions.",
            },
            {
                id: 2,
                image: "/assets/img/icons/red/ochrona1.svg",
                title: "Proactive Approach",
                desc: "Regular support enables anticipating and addressing threats.",
            },
        ],
        FAQLeft: [
            {
                id: 1,
                title: "What is incident response support?",
                content: "This service includes rapid response to security incidents and assistance in analyzing and resolving them.",
            },
            {
                id: 2,
                title: "What incidents does the support cover?",
                content: "All cybersecurity-related incidents, such as DDoS attacks, phishing, data leaks, or malware.",
            },
            {
                id: 3,
                title: "Is the service available 24/7?",
                content: "Yes, we offer support on a round-the-clock basis to quickly respond to threats.",
            },
            {
                id: 4,
                title: "What does the incident response process look like?",
                content: "Situation analysis, implementation of corrective actions, reporting, and advice on preventing similar incidents.",
            },
            {
                id: 5,
                title: "Does the service help meet regulatory requirements?",
                content: "Yes, our support considers compliance with regulations such as GDPR or NIS2.",
            },
            {
                id: 6,
                title: "Do you offer training after incident resolution?",
                content: "Yes, we can conduct training to increase awareness and preparedness among staff.",
            },
        ],
        FAQRight: [
            {
                id: 7,
                title: "Does the service cover all types of businesses?",
                content: "Yes, we provide support for both small businesses and large corporations.",
            },
            {
                id: 8,
                title: "Do you provide reports after an incident?",
                content: "Yes, reports include a detailed analysis and corrective recommendations.",
            },
            {
                id: 9,
                title: "How quickly do you respond to a report?",
                content: "We respond immediately after receiving a report from the client.",
            },
            {
                id: 10,
                title: "Does the service include evidence preservation?",
                content: "Yes, we assist in preserving evidence for further analysis or legal proceedings.",
            },
            {
                id: 11,
                title: "Can the service be part of a business continuity plan?",
                content: "Yes, incident response support can be an integral part of a continuity strategy.",
            },
            {
                id: 12,
                title: "Does the service include recommendations for the future?",
                content: "Yes, we provide guidance to help enhance security in the future.",
            },
        ],
        filter: "obslugaincydentow",
        filter2: "subscription",
    },
    {
        id: "III_linia_wsparcia_technicznego",
        title: "Third-Line Technical Support",
        title2: "",
        titleAboutService: "Why should you use third-line technical support?",
        url: "/dashboard/red/services/III_linia_wsparcia_technicznego",
        urlImage: "/assets/img/red/parciple/technical.svg",
        headerImg: "/assets/img/red/services/podatnosc.png",
        position: "center",
        size: 0.65,
        description: "Our third-line technical support service provides comprehensive assistance in resolving advanced technical issues.\n\nOur specialists possess expert knowledge, enabling them to quickly diagnose problems, develop solutions, and minimize IT system downtime.\n\nSupport includes ticket analysis, implementation of fixes, technical advice, and collaboration with software and hardware vendors to resolve complex incidents.\n\nThird-line technical support ensures that even the most demanding problems are quickly and effectively resolved.",
        titleKrzysci: "Benefits of third-line technical support:",
        titleZagrozenia: "Risks of lacking adequate support:",
        // Icons BLUE
        iconsTop: [
            {
                id: 1,
                image: "/assets/img/icons/zabezpieczenie.svg",
                title: "Fast Diagnosis",
                desc: "Immediate recognition and analysis of technical issues.",
            },
            {
                id: 2,
                image: "/assets/img/icons/monitoring.png",
                title: "Expert Knowledge",
                desc: "Access to specialists with years of experience.",
            },
            {
                id: 3,
                image: "/assets/img/icons/ochrona.svg",
                title: "In-Depth Analysis",
                desc: "Detailed analysis of problems requiring advanced technical expertise.",
            },
            {
                id: 4,
                image: "/assets/img/icons/rodo.svg",
                title: "Technical Advice",
                desc: "Recommendations for optimizing IT systems.",
            },
            {
                id: 5,
                image: "/assets/img/icons/zaufanie.svg",
                title: "Vendor Collaboration",
                desc: "Coordination with software and hardware providers.",
            },
            {
                id: 6,
                image: "/assets/img/icons/zapobieganie.svg",
                title: "Minimized Downtime",
                desc: "Quick problem resolution reduces work disruptions.",
            },
        ],
        iconsRed: [
            {
                id: 1,
                image: "/assets/img/icons/utrata.svg",
                title: "Extended Downtime",
                desc: "Technical issues can lead to prolonged disruptions.",
            },
            {
                id: 2,
                image: "/assets/img/icons/kara.svg",
                title: "Risk of Data Loss",
                desc: "Failure to act appropriately can lead to loss of critical information.",
            },
            {
                id: 3,
                image: "/assets/img/icons/ryzyko.svg",
                title: "Financial Costs",
                desc: "Inefficient problem management generates unnecessary expenses.",
            },
            {
                id: 4,
                image: "/assets/img/icons/przestoje.png",
                title: "Reputational Damage",
                desc: "Technical issues may affect the organization's image.",
            },
            {
                id: 5,
                image: "/assets/img/icons/kradziez.svg",
                title: "Problem Escalation",
                desc: "Lack of professional help can worsen the situation.",
            },
            {
                id: 6,
                image: "/assets/img/icons/kontrola.svg",
                title: "Improper Solutions",
                desc: "Problems may be misdiagnosed or incorrectly resolved.",
            },
        ],
        doZapamietaniaTop: [
            {
                id: 1,
                image: "/assets/img/icons/red/zapobieganie1.svg",
                title: "Quick Reaction",
                desc: "Experts ensure immediate action during critical situations.",
            },
            {
                id: 2,
                image: "/assets/img/icons/red/zabezpieczenie1.svg",
                title: "Comprehensive Support",
                desc: "Help in resolving even the most complex issues.",
            },
        ],
        doZapamietaniaBottom: [
            {
                id: 1,
                image: "/assets/img/icons/red/rodo1.svg",
                title: "System Compliance",
                desc: "Support ensures adherence to best industry practices.",
            },
            {
                id: 2,
                image: "/assets/img/icons/red/ochrona1.svg",
                title: "Solution Optimization",
                desc: "Helps implement more efficient and secure technologies.",
            },
        ],
        FAQLeft: [
            {
                id: 1,
                title: "What is third-line technical support?",
                content: "It is the highest level of support focused on resolving the most complex technical issues.",
            },
            {
                id: 2,
                title: "Who can benefit from this service?",
                content: "The service is intended for companies that require advanced IT support.",
            },
            {
                id: 3,
                title: "What issues does third-line support cover?",
                content: "Problems related to IT infrastructure, software, networks, and security.",
            },
            {
                id: 4,
                title: "Does support include vendor collaboration?",
                content: "Yes, we collaborate with vendors to resolve hardware and software issues.",
            },
            {
                id: 5,
                title: "Is the service available 24/7?",
                content: "Yes, we offer 24/7 support depending on the client's needs.",
            },
            {
                id: 6,
                title: "What are the benefits of this service?",
                content: "Quick diagnosis, minimized downtime, and system optimization.",
            },
        ],
        FAQRight: [
            {
                id: 7,
                title: "Can I use the service on an ad-hoc basis?",
                content: "Yes, we offer both ongoing and ad-hoc support depending on your needs.",
            },
            {
                id: 8,
                title: "Does the service include training?",
                content: "Yes, we can also conduct training for IT teams on problem-solving.",
            },
            {
                id: 9,
                title: "Does support include system audits?",
                content: "Yes, we can perform audits to identify potential issues.",
            },
            {
                id: 10,
                title: "How quickly can support be initiated?",
                content: "Support is available as soon as a problem is reported.",
            },
            {
                id: 11,
                title: "Does the service help with compliance?",
                content: "Yes, support helps ensure compliance with regulations like GDPR or NIS2.",
            },
            {
                id: 12,
                title: "Does the service include reporting?",
                content: "Yes, we provide detailed reports after resolving issues.",
            },
        ],
        filter: "obslugaincydentow",
        filter2: "subscription",
    },
    {
        id: "cykliczne_testy_socjotechniczne",
        title: "Periodic Social Engineering Tests",
        title2: "",
        titleAboutService: "Why should you invest in periodic social engineering tests?",
        url: "/dashboard/red/services/cykliczne_testy_socjotechniczne",
        urlImage: "/assets/img/red/parciple/safe.png",
        headerImg: "/assets/img/red/services/podatnosc.png",
        position: "center",
        size: 1.1,
        description: "Periodic social engineering tests are designed to assess and improve employee awareness of potential social engineering threats, such as phishing, baiting, and pretexting.\n\nThese tests help organizations identify vulnerabilities in human behavior, enabling tailored training programs and reinforcing security measures.\n\nBy regularly conducting these tests, organizations can foster a culture of cybersecurity, mitigate risks associated with human error, and build a more resilient workforce against manipulative cyber threats.",
        titleKrzysci: "Benefits of periodic social engineering tests:",
        titleZagrozenia: "Risks of not conducting social engineering tests:",
        //icon BLUE
        iconsTop: [
            {
                id: 1,
                image: "/assets/img/icons/zabezpieczenie.svg",
                title: "Increased Awareness",
                desc: "Enhances employee understanding of potential social engineering attacks.",
            },
            {
                id: 2,
                image: "/assets/img/icons/monitoring.png",
                title: "Proactive Defense",
                desc: "Prepares employees to recognize and counteract manipulative tactics.",
            },
            {
                id: 3,
                image: "/assets/img/icons/ochrona.svg",
                title: "Improved Training",
                desc: "Identifies knowledge gaps to focus training efforts effectively.",
            },
            {
                id: 4,
                image: "/assets/img/icons/rodo.svg",
                title: "Regulatory Compliance",
                desc: "Supports adherence to industry standards and regulations.",
            },
            {
                id: 5,
                image: "/assets/img/icons/zaufanie.svg",
                title: "Reinforced Trust",
                desc: "Builds confidence among stakeholders through proactive risk management.",
            },
            {
                id: 6,
                image: "/assets/img/icons/zapobieganie.svg",
                title: "Enhanced Security",
                desc: "Strengthens organizational resilience against internal and external threats.",
            },
        ],

        //red
        iconsRed: [
            {
                id: 1,
                image: "/assets/img/icons/utrata.svg",
                title: "Increased Risk of Phishing",
                desc: "Higher likelihood of employees falling victim to phishing attacks.",
            },
            {
                id: 2,
                image: "/assets/img/icons/kara.svg",
                title: "Data Leaks",
                desc: "Greater risk of sensitive information being compromised.",
            },
            {
                id: 3,
                image: "/assets/img/icons/ryzyko.svg",
                title: "Operational Interruptions",
                desc: "Disruptions caused by successful social engineering attacks.",
            },
            {
                id: 4,
                image: "/assets/img/icons/przestoje.png",
                title: "Reputational Damage",
                desc: "Loss of customer trust due to preventable incidents.",
            },
            {
                id: 5,
                image: "/assets/img/icons/kradziez.svg",
                title: "Increased Penalties",
                desc: "Fines for failing to meet compliance requirements.",
            },
            {
                id: 6,
                image: "/assets/img/icons/kontrola.svg",
                title: "Awareness Gaps",
                desc: "Employees remain unaware of how to respond to threats effectively.",
            },
        ],
        doZapamietaniaTop: [
            {
                id: 1,
                image: "/assets/img/icons/red/zapobieganie1.svg",
                title: "Proactive Measures",
                desc: "Social engineering tests encourage employees to stay vigilant.",
            },
            {
                id: 2,
                image: "/assets/img/icons/red/zabezpieczenie1.svg",
                title: "Compliance",
                desc: "Ensures adherence to regulatory and industry requirements.",
            },
        ],
        doZapamietaniaBottom: [
            {
                id: 1,
                image: "/assets/img/icons/red/rodo1.svg",
                title: "Improved Awareness",
                desc: "Tests enhance understanding of potential threats and responses.",
            },
            {
                id: 2,
                image: "/assets/img/icons/red/ochrona1.svg",
                title: "Strengthened Security",
                desc: "Builds a culture of awareness and resilience against attacks.",
            },
        ],
        FAQLeft: [
            {
                id: 1,
                title: "What are social engineering tests?",
                content: "They simulate manipulative attacks to assess employee susceptibility and improve awareness.",
            },
            {
                id: 2,
                title: "What tactics are used in these tests?",
                content: "Techniques include phishing, baiting, pretexting, and tailgating.",
            },
            {
                id: 3,
                title: "Are these tests confidential?",
                content: "Yes, all results and details remain confidential and are used only for improving organizational security.",
            },
            {
                id: 4,
                title: "How are tests conducted?",
                content: "The process includes planning, simulation, analysis, and reporting on findings.",
            },
            {
                id: 5,
                title: "How often should these tests be conducted?",
                content: "We recommend conducting them periodically, at least annually or after significant organizational changes.",
            },
            {
                id: 6,
                title: "Can tests be tailored to the organization?",
                content: "Yes, tests can be customized to match the specific needs and risks of your organization.",
            },
        ],
        FAQRight: [
            {
                id: 7,
                title: "What are the benefits of social engineering tests?",
                content: "They improve employee awareness, reduce risk, and strengthen overall security posture.",
            },
            {
                id: 8,
                title: "Are these tests legal?",
                content: "Yes, they are conducted ethically and with organizational approval.",
            },
            {
                id: 9,
                title: "Do tests cover remote employees?",
                content: "Yes, tests can include scenarios involving remote workers.",
            },
            {
                id: 10,
                title: "How do tests enhance training programs?",
                content: "By identifying gaps in awareness, tests help tailor training to address specific vulnerabilities.",
            },
            {
                id: 11,
                title: "Can test results lead to additional services?",
                content: "Yes, based on the results, we can recommend additional training or security measures.",
            },
            {
                id: 12,
                title: "Do you provide reports after the tests?",
                content: "Yes, detailed reports with findings and recommendations are provided after the tests.",
            },
        ],
        filter: "testy",
        filter2: "subscription",
    }
]